/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "LettingsOpsDatabaseUrl": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LettingsOpsEmailBucket": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "LettingsOpsEmailDomain": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "LettingsOpsOpenAIKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "lettings-api": {
      "type": "sst.aws.ApiGatewayV2"
      "url": string
    }
    "web": {
      "type": "sst.aws.StaticSite"
      "url": string
    }
  }
}
/// <reference path="sst-env.d.ts" />

import "sst"
export {}